site_name: Ressources NSI & SNT

theme:
  name: material
  features:
    - navigation.tabs

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg