site_name: Ressources NSI & SNT

theme:
  name: material

  palette:
    - scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Passer au mode sombre

    - scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Passer au mode clair

  features:
    - navigation.tabs

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: © 2026 Lucas Lecouvez